--
-- PostgreSQL database dump
--

-- Dumped from database version 15.7
-- Dumped by pg_dump version 16.3

-- Started on 2025-03-15 22:56:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 25845)
-- Name: projects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.projects (
    id integer NOT NULL,
    created_at date,
    description character varying(5000),
    title character varying(255),
    updated_at date,
    reset_token character varying(255)
);


ALTER TABLE public.projects OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 25844)
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 25853)
-- Name: user_dtls; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_dtls (
    id integer NOT NULL,
    nrc character varying(255),
    email character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255),
    role character varying(255),
    account_non_locked boolean,
    failed_attempt integer,
    is_enable boolean,
    lock_time timestamp(6) without time zone,
    reset_token character varying(255)
);


ALTER TABLE public.user_dtls OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 25852)
-- Name: user_dtls_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_dtls_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_dtls_id_seq OWNER TO postgres;

--
-- TOC entry 3334 (class 0 OID 0)
-- Dependencies: 216
-- Name: user_dtls_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_dtls_id_seq OWNED BY public.user_dtls.id;


--
-- TOC entry 3178 (class 2604 OID 25856)
-- Name: user_dtls id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_dtls ALTER COLUMN id SET DEFAULT nextval('public.user_dtls_id_seq'::regclass);


--
-- TOC entry 3326 (class 0 OID 25845)
-- Dependencies: 215
-- Data for Name: projects; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.projects (id, created_at, description, title, updated_at, reset_token) FROM stdin;
2	2025-03-13	In this example, LocalDate , LocalDateTime , and LocalTime are used to represent the respective date types in Java. When you save an instance of the Event class, Spring Boot will handle the conversion to the appropriate SQL data types automatically.	Storing Dates in a Database Using Spring Boot	2025-03-13	\N
3	2025-03-13	Similar to the contextual text color classes, easily set the background of an element to any contextual class. Anchor components will darken on hover, just like the text 	Background color	2025-03-14	\N
4	2025-03-15	A database is an organized collection of structured information, or data, typically stored electronically in a computer system, designed for efficient storage, retrieval, and management of data. 	DataBase	\N	\N
\.


--
-- TOC entry 3328 (class 0 OID 25853)
-- Dependencies: 217
-- Data for Name: user_dtls; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_dtls (id, nrc, email, name, password, phone, role, account_non_locked, failed_attempt, is_enable, lock_time, reset_token) FROM stdin;
4	\N	nilar@gmail.com	nilar	$2a$10$MpVtt1E2E9U5rM77fAz4CuCP.UQK0/A7Gnh0zqG1EjDRtjUejah.S	475734	ROLE_USER	t	0	t	\N	\N
6	\N	admin@gmail.com	admin	$2a$10$Uh5/FLaX7BFB4cHY5K254.sb8aTW.G3QNwraTTx9fLsORj7g2iClS	959569847622	ROLE_ADMIN	t	0	t	\N	\N
2	5/gfhghfhjg	robin@gmail.com	robin	$2a$10$KFrYePc4Vq8AMNhue/MtF.EpTzG5xF92CQpBApvPVF66QsS4LSLsO	57457458	ROLE_USER	t	0	t	\N	\N
\.


--
-- TOC entry 3335 (class 0 OID 0)
-- Dependencies: 214
-- Name: projects_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.projects_id_seq', 5, true);


--
-- TOC entry 3336 (class 0 OID 0)
-- Dependencies: 216
-- Name: user_dtls_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_dtls_id_seq', 6, true);


--
-- TOC entry 3180 (class 2606 OID 25851)
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- TOC entry 3182 (class 2606 OID 25860)
-- Name: user_dtls user_dtls_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_dtls
    ADD CONSTRAINT user_dtls_pkey PRIMARY KEY (id);


-- Completed on 2025-03-15 22:56:17

--
-- PostgreSQL database dump complete
--

